const LEADERSHIP_PRINCIPLE = "LEADERSHIP_PRINCIPLE";
const THOUGHT_PARADIGM = "THOUGHT_PARADIGM";
const LEADERSHIP_STYLE = "LEADERSHIP_STYLE";
const NAME = "NAME";
const POSITION = "POSITION";
const BACKGROUND = "BACKGROUND";
const LEGACY = "LEGACY";

export { LEADERSHIP_PRINCIPLE, THOUGHT_PARADIGM, LEADERSHIP_STYLE, NAME, POSITION, BACKGROUND, LEGACY };
