const NAME = "NAME";
const POSITION = "POSITION";
const BACKGROUND = "BACKGROUND";
const LEGACY = "LEGACY";
const LEADERSHIP_PRINCIPLE = "LEADERSHIP_PRINCIPLE";
const THOUGHT_PARADIGM = "THOUGHT_PARADIGM";
const LEADERSHIP_STYLE = "LEADERSHIP_STYLE";

module.exports = {
    NAME,
    POSITION,
    BACKGROUND,
    LEGACY,
    LEADERSHIP_PRINCIPLE,
    THOUGHT_PARADIGM,
    LEADERSHIP_STYLE
};