const SUCCESS_STATUS_CODE = 200;
const ERROR_STATUS_CODE = 500;
const BAD_REQUEST_STATUS_CODE = 400;

const TAlENT_TANK_TYPE = "TALENT";
const PITCH_TANK_TYPE = "PITCH";
const PRODUCT_TANK_TYPE = "PRODUCT";

const TANK_TYPES = [TAlENT_TANK_TYPE, PITCH_TANK_TYPE, PRODUCT_TANK_TYPE];

module.exports = {
    SUCCESS_STATUS_CODE,
    ERROR_STATUS_CODE,
    BAD_REQUEST_STATUS_CODE,
    TAlENT_TANK_TYPE,
    PITCH_TANK_TYPE,
    PRODUCT_TANK_TYPE,
    TANK_TYPES
};